@startuml
    entity User {
    
        userId--
        name
        age
        userType
        meetingPreference
        latitude
        longitude
        necessities
    }

    entity Necessity{
        
        necessityId--
        name
    }

    entity Meeting {
        
        meetingId--
        date
        longitude
        latitude
        inPerson
        description
        participants
    }

    Meeting --> User
    Necessity --> User

@enduml